language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install coveralls --use-mirrors && export HAS_COVERALLS=1; fi

script:
  - nosetests -q --with-coverage --cover-erase --cover-package=unicards

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
